// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (onyl share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavors')
require('./7-mind-grenade')

// sayHi('Murat')
// sayHi(names.john)
// sayHi(names.peter)
